# Confirming overlap between NYCHA violation data and General building violation data

In [3]:
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv()

True

In [ ]:
nycha_df = pd.read_csv("../data/nycha.csv")
app_token = os.getenv("TOKEN_KEY")

### Getting NYCHA BINS

In [5]:
nycha_df['BIN'].shape

(2391,)

In [6]:
nycha_bins = nycha_df['BIN'].dropna().unique().tolist()
nycha_bins = [int(x) for x in nycha_bins]
len(nycha_bins)

226

### Creating params

In [7]:
id_list = ", ".join(f"'{b}'" for b in nycha_bins)

In [ ]:
hpd_violations = pd.read_csv('../data/Housing_Maintenance_Code_Violations.csv')

/var/folders/xv/zb6mjv_93435jvb4s_wsh3xm0000gn/T/ipykernel_54933/671917896.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  hpd_violations = pd.read_csv('data/Housing_Maintenance_Code_Violations.csv')

In [9]:
hpd_violations.columns

Index(['ViolationID', 'BuildingID', 'RegistrationID', 'BoroID', 'Borough',
       'HouseNumber', 'LowHouseNumber', 'HighHouseNumber', 'StreetName',
       'StreetCode', 'Postcode', 'Apartment', 'Story', 'Block', 'Lot', 'Class',
       'InspectionDate', 'ApprovedDate', 'OriginalCertifyByDate',
       'OriginalCorrectByDate', 'NewCertifyByDate', 'NewCorrectByDate',
       'CertifiedDate', 'OrderNumber', 'NOVID', 'NOVDescription',
       'NOVIssuedDate', 'CurrentStatusID', 'CurrentStatus',
       'CurrentStatusDate', 'NovType', 'ViolationStatus', 'RentImpairing',
       'Latitude', 'Longitude', 'CommunityBoard', 'CouncilDistrict',
       'CensusTract', 'BIN', 'BBL', 'NTA'],
      dtype='object')

In [1]:
hpd_w_NYCHA_bins = hpd_violations[hpd_violations['BIN'].isin(nycha_bins)]

NameError: name 'hpd_violations' is not defined

In [11]:
print(hpd_w_NYCHA_bins.shape)
len(hpd_w_NYCHA_bins['BIN'].unique())

(425, 41)

72

In [12]:
print(nycha_df['BIN'].dtype)
print(hpd_violations['BIN'].dtype)

float64
float64

In [13]:
hpd_violations['BIN'].isnull().sum()

hpd_violations.shape

(10747007, 41)

In [14]:
print(nycha_df.columns.tolist())
print(nycha_df.shape)

['Violation ID', 'Primary Building Identifier', 'Primary Boro Identifier', 'Primary Borough Name', 'Primary House Number', 'Primary Low House Number', 'Primary High House Number', 'Primary Street Name', 'Primary Postcode', 'Development Name', 'TDS Number', 'Stairhall Number', 'NYCHA Address Section BoroID', 'NYCHA Address Section Borough', 'NYCHA Address Section House Number', 'NYCHA Address Section Street Name', 'NYCHA Address Section PostCode', 'Apartment', 'Story', 'Block', 'Lot', 'Violation Description', 'Class', 'Inspection Date', 'Approved Date', 'Order Number', 'Issued in Error', 'Latitude', 'Longitude', 'Community Board', 'Council District', 'BIN', 'BBL', 'Census Tract (2020)', 'Neighborhood Tabulation Area (NTA) (2020)']
(2391, 35)

In [15]:
# BIN in nycha is float64 (e.g. 1234567.0), convert to nullable int then string
nycha_df["BIN_key"] = nycha_df["BIN"].astype("Int64").astype(str)

# BIN in large dataset is object — strip any whitespace/decimals just in case
hpd_violations["BIN_key"] = hpd_violations["BIN"].astype("Int64").astype(str).str.strip()

# check they look the same now
print(nycha_df["BIN_key"].head(10).tolist())
print(hpd_violations["BIN_key"].head(10).tolist())

['3326207', '3326207', '3326207', '3321415', '3321415', '3321415', '3321415', '3321415', '3321415', '3321415']
['<NA>', '<NA>', '<NA>', '<NA>', '<NA>', '<NA>', '<NA>', '<NA>', '<NA>', '2099579']

In [16]:
small_bins = set(nycha_df["BIN_key"].dropna())
large_bins = set(hpd_violations["BIN_key"].dropna())

matched_bins = small_bins & large_bins
print(f"NYCHA BINs:         {len(small_bins)}")
print(f"Matched in large:   {len(matched_bins)}")
print(f"Match rate:         {len(matched_bins)/len(small_bins)*100:.1f}%")

NYCHA BINs:         227
Matched in large:   73
Match rate:         32.2%

In [17]:
hpd_violations.tail()

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,BIN_key
10747002,9984323,52028,201562,2,BRONX,2700,2700,2736,BRONX PARK EAST,15220,...,N,40.865552,-73.870416,11.0,12.0,33601.0,2093450.0,2.045060e+09,Allerton,2093450
10747003,9984324,52028,201562,2,BRONX,2700,2700,2736,BRONX PARK EAST,15220,...,N,40.865552,-73.870416,11.0,12.0,33601.0,2093450.0,2.045060e+09,Allerton,2093450
10747004,9984325,52028,201562,2,BRONX,2700,2700,2736,BRONX PARK EAST,15220,...,N,40.865552,-73.870416,11.0,12.0,33601.0,2093450.0,2.045060e+09,Allerton,2093450
10747005,9984326,52028,201562,2,BRONX,2700,2700,2736,BRONX PARK EAST,15220,...,N,40.865552,-73.870416,11.0,12.0,33601.0,2093450.0,2.045060e+09,Allerton,2093450
10747006,9984327,52028,201562,2,BRONX,2700,2700,2736,BRONX PARK EAST,15220,...,N,40.865552,-73.870416,11.0,12.0,33601.0,2093450.0,2.045060e+09,Allerton,2093450

#### Check if addresses line up within the matched BINs. Get Matched HPD Bins and Matched NYCHA Bins and compare

In [18]:
hpd_w_NYCHA_bins.head()

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,ViolationStatus,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
102564,1496097,299534,391686,3,BROOKLYN,708,708,720,GATES AVENUE,43330,...,Open,N,40.687885,-73.935997,3.0,36.0,293.0,3044630.0,3.016350e+09,Bedford-Stuyvesant (East)
102565,1496098,299534,391686,3,BROOKLYN,708,708,720,GATES AVENUE,43330,...,Open,N,40.687885,-73.935997,3.0,36.0,293.0,3044630.0,3.016350e+09,Bedford-Stuyvesant (East)
102577,1496101,299534,391686,3,BROOKLYN,708,708,720,GATES AVENUE,43330,...,Open,N,40.687885,-73.935997,3.0,36.0,293.0,3044630.0,3.016350e+09,Bedford-Stuyvesant (East)
141905,18286532,989617,391687,3,BROOKLYN,730,722,740,GATES AVENUE,43330,...,Close,N,40.687970,-73.935297,3.0,36.0,293.0,3426336.0,3.016350e+09,Bedford-Stuyvesant (East)
212171,18591622,989617,391687,3,BROOKLYN,730,722,740,GATES AVENUE,43330,...,Open,N,40.687970,-73.935297,3.0,36.0,293.0,3426336.0,3.016350e+09,Bedford-Stuyvesant (East)

In [19]:
# give me records from nycha_df where the bin exists in matched_bins
matched_nycha_bins = nycha_df[nycha_df['BIN_key'].isin(list(matched_bins))]

In [20]:
matched_nycha_bins.head()

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020),BIN_key
0,18220152,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1,18220153,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
2,18220154,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
20,18220066,217152,3,BROOKLYN,483,483,509,CARLTON AVENUE,11238,ATLANTIC TERMINAL SITE 4B,...,N,40.683189,-73.970853,302,35,3057520.0,3.020070e+09,179,BK0203,3057520
21,18220067,217152,3,BROOKLYN,483,483,509,CARLTON AVENUE,11238,ATLANTIC TERMINAL SITE 4B,...,N,40.683189,-73.970853,302,35,3057520.0,3.020070e+09,179,BK0203,3057520

In [21]:
matched_nycha_bins[matched_nycha_bins['BIN_key'] == '3326207']

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020),BIN_key
0,18220152,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1,18220153,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
2,18220154,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
23,18220149,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
24,18220150,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
25,18220151,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1204,18348421,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1205,18348422,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1206,18348423,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1207,18348424,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1208,18348425,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
1209,18348426,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
2220,18622391,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207
2230,18622392,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601,3326207

In [22]:
hpd_w_NYCHA_bins["BIN_key"] = hpd_w_NYCHA_bins["BIN"].astype("Int64").astype(str).str.strip()

hpd_w_NYCHA_bins[hpd_w_NYCHA_bins['BIN_key'] == '3326207']

/var/folders/xv/zb6mjv_93435jvb4s_wsh3xm0000gn/T/ipykernel_54933/914154204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_w_NYCHA_bins["BIN_key"] = hpd_w_NYCHA_bins["BIN"].astype("Int64").astype(str).str.strip()

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,BIN_key
8302466,5655038,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8302467,5655039,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8302468,5655040,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8302469,5655041,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,Y,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8668822,8119910,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8668826,8119914,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207
8668827,8119915,808768,399995,3,BROOKLYN,1,1,17,LORRAINE STREET,57170,...,N,40.675118,-74.009568,6.0,38.0,85.0,3326207.0,3.005330e+09,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,3326207

In [24]:
#column data type conversion
hpd_violations['Story'] = hpd_violations['Story'].astype(str)

hpd_violations.to_parquet("data/hpd_violations.parquet")

In [ ]:
# pd.DataFrame({'a': [1,2,3]}).to_parquet('test.parquet')

In [ ]:
# import sys
# sys.executable